# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bb9b5ce8df3327cd5c112dbf2017be1b3d4735b7e973a763b41d811b34d8dac276e16276be278bf54ab02b34eeb2ea65ff50b41b6f40943430dcd83bb0b5524b

test:
  secret_key_base: a3d5297a1a254804f461e033b0054846b44b55b9c663f33d4509d2f0af3084b446206db03dfce6ca08f7552373ec9bd49495226d2b36b677e27aec5d7c2896c8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
